id: c7d2bb7c-212b-4e3e-8679-04f266c5f23a
post_type: video
title: Starknet Mandarin Bootcamp - Starknet Decentralized Applications 06
published_date: 2024-02-12T09:55:28.242Z
video:
  url: https://www.youtube.com/watch?v=MOXruR-Q5as&list=PLsWAMtU54z7s12-kdLwubwupCg2F3Ckq7&index=6
  id: MOXruR-Q5as
  data:
    kind: youtube#video
    etag: JftmfO8qtsMWcjkcEABCtwXrbK8
    id: MOXruR-Q5as
    snippet:
      publishedAt: 2024-02-05T01:01:28.000Z
      liveBroadcastContent: none
      thumbnails:
        default:
          url: https://i.ytimg.com/vi/MOXruR-Q5as/default.jpg
          width: 120
          height: 90
        medium:
          url: https://i.ytimg.com/vi/MOXruR-Q5as/mqdefault.jpg
          width: 320
          height: 180
        high:
          url: https://i.ytimg.com/vi/MOXruR-Q5as/hqdefault.jpg
          width: 480
          height: 360
        standard:
          url: https://i.ytimg.com/vi/MOXruR-Q5as/sddefault.jpg
          width: 640
          height: 480
        maxres:
          url: https://i.ytimg.com/vi/MOXruR-Q5as/maxresdefault.jpg
          width: 1280
          height: 720
      channelTitle: WTF Academy
      title: 【Starknet中文训练营】06 Starknet去中心化应用
      categoryId: "28"
      localized:
        title: 【Starknet中文训练营】06 Starknet去中心化应用
        description: >-
          #starknet 


          🦄 Starknet中文训练营：一场为期7周的在线培训项目，专为开发者而设。


          👑 旨在帮助开发者在以太坊Layer2 Starknet上开发应用🎫


          💎 本活动由 WTF Academy 主办，Starknet中文社区 协办，Starknet基金会支持。


          ⏰ 日期： 2023年11月12日至12月22日，每周五晚8点，线上举行


          💻 为了提高教学质量，本次训练营限制100人参与，报名截止日期：11月11日


          💰 完成课程的学员将获得链上证书；优秀学员将获得奖学金，并且我们将协助申请Starknet早期社区成员计划（ECMP）


          本期视频为第六讲 - Starknet去中心化应用

          主讲人 - Daxiong


          【Starknet中文训练营】播放列表

          https://www.youtube.com/playlist?list=PLsWAMtU54z7s12-kdLwubwupCg2F3Ckq7
      description: |-
        #starknet 

        🦄 Starknet中文训练营：一场为期7周的在线培训项目，专为开发者而设。

        👑 旨在帮助开发者在以太坊Layer2 Starknet上开发应用🎫

        💎 本活动由 WTF Academy 主办，Starknet中文社区 协办，Starknet基金会支持。

        ⏰ 日期： 2023年11月12日至12月22日，每周五晚8点，线上举行

        💻 为了提高教学质量，本次训练营限制100人参与，报名截止日期：11月11日

        💰 完成课程的学员将获得链上证书；优秀学员将获得奖学金，并且我们将协助申请Starknet早期社区成员计划（ECMP）

        本期视频为第六讲 - Starknet去中心化应用
        主讲人 - Daxiong

        【Starknet中文训练营】播放列表
        https://www.youtube.com/playlist?list=PLsWAMtU54z7s12-kdLwubwupCg2F3Ckq7
      channelId: UC25f24G5Zb4aQ4hLr1poitw
    contentDetails:
      duration: PT1H34M2S
      dimension: 2d
      definition: hd
      caption: "false"
      licensedContent: false
      contentRating: {}
      projection: rectangular
image: /assets/maxresdefault-15.jpg
category:
  - stark-math
  - 3fe387e2-1fb6-41b9-bb74-96d6df394f42
topic:
  - getting-started
short_desc: >-
  Starknet Chinese Training Camp: A 7-week online training program specifically
  designed for developers.


  The goal is to aid developers in creating applications on Ethereum Layer2 Starknet.


  This event is organized by WTF Academy in cooperation with the Starknet Chinese Community and supported by the Starknet Foundation.


  This session's video is the sixth lecture - Starknet Decentralized Applications.

  Speaker - Daxiong
